# Generated by Django 2.2.19 on 2022-03-29 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Полных лет')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('bio', models.TextField(blank=True, help_text='Раскажите о себе', max_length=300, null=True, verbose_name='Обо мне')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Город')),
                ('image', models.ImageField(blank=True, help_text='Загрузите картинку', null=True, upload_to='avatar/', verbose_name='Картинка')),
                ('avatar', models.ImageField(blank=True, help_text='Загрузите аватарку', null=True, upload_to='avatar/', verbose_name='Аватарка')),
                ('job', models.CharField(blank=True, max_length=100, null=True, verbose_name='Место работы')),
                ('number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Телефон')),
                ('github', models.CharField(blank=True, max_length=100, null=True)),
                ('telegram', models.CharField(blank=True, max_length=100, null=True)),
                ('vk', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
