# Generated by Django 2.2.28 on 2022-12-20 13:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ski',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(default='Лыжный курорт', max_length=100, verbose_name='Лыжный курорт')),
                ('cr', models.IntegerField(default=100000, verbose_name='Деньги')),
                ('hotel', models.IntegerField(default=1, verbose_name='Отель')),
                ('hotel_in_demand', models.BooleanField(default=False, verbose_name='Отель востребован')),
                ('restauran', models.IntegerField(default=1, verbose_name='Ресторан')),
                ('restauran_in_demand', models.BooleanField(default=False, verbose_name='Ресторан востребован')),
                ('low_track', models.IntegerField(default=1, verbose_name='Маленькая горка')),
                ('low_track_in_demand', models.BooleanField(default=False, verbose_name='Маленькая горка востребована')),
                ('middle_track', models.IntegerField(default=0, verbose_name='Средняя горка')),
                ('high_track', models.IntegerField(default=0, verbose_name='Большая горка')),
                ('high_track_in_demand', models.BooleanField(default=False, verbose_name='Большая горка востребована')),
                ('lift', models.IntegerField(default=1, verbose_name='Подьемник')),
                ('kupe_lift', models.IntegerField(default=0, verbose_name='Кабиночный подьемник')),
                ('lift_in_demand', models.BooleanField(default=False, verbose_name='Подьемники востребованы')),
                ('advertising', models.IntegerField(default=0, verbose_name='Расходы на рекламу')),
                ('popularity', models.IntegerField(default=50, verbose_name='Популярность курорта')),
                ('day', models.IntegerField(default=0, verbose_name='День')),
                ('data_today', models.DateField(default=datetime.datetime(3022, 12, 20, 16, 0, 1, 504774), verbose_name='Сегодняшний день')),
                ('newbie', models.IntegerField(default=20, verbose_name='Новичек')),
                ('professional', models.IntegerField(default=0, verbose_name='Профессионал')),
                ('old_newbie', models.IntegerField(default=0, verbose_name='Новичков было')),
                ('old_professional', models.IntegerField(default=0, verbose_name='Профессионалов было')),
                ('left_newbie', models.IntegerField(default=0, verbose_name='Уехало новичков')),
                ('left_professional', models.IntegerField(default=0, verbose_name='Уехало Профессионалов')),
                ('arrived_newbie', models.IntegerField(default=0, verbose_name='Приехало новичков')),
                ('arrived_professional', models.IntegerField(default=0, verbose_name='Приехало Профессионалов')),
                ('cr_newbie', models.IntegerField(default=0, verbose_name='деньги от новичков')),
                ('cr_professional', models.IntegerField(default=0, verbose_name='деньги от профессионалов')),
                ('cr_building', models.IntegerField(default=0, verbose_name='Содержание построек')),
                ('cr_track', models.IntegerField(default=10000, verbose_name='Содержание трасс')),
                ('count_building', models.IntegerField(default=0, verbose_name='Построек за день')),
                ('finish', models.BooleanField(default=False, verbose_name='Конец игры')),
            ],
        ),
    ]
